"""Market layer: published auction values, with basis and lineage.

Revision ID: 0018
Revises: 0017
Create Date: 2026-08-21

``aav-source``, Phase 8 track A. Four new tables at ``data_layer = 'market'``:
what somebody else published, on what basis, derived from what.

Deliberately *not* an extension of ``projection_sources``. That table's
``projection_provider_namespace`` CHECK admits five projection publishers, and
the publishers that print auction values are mostly not among them; ADR-008 is
Accepted and ``plan.md`` states the boundary directly — "a seeded AAV is market
evidence, not a valuation input". The backlog entry for ``aav-source`` said
otherwise and predates the ADR; it has been amended to record the ruling.

All four tables are new, so every CHECK is inline in ``CREATE TABLE`` and no
``batch_alter_table`` is required. That matters: ``gates.md`` records an
incident where adding a CHECK to an *existing* table forced SQLite's
copy-drop-rename rebuild, and ten foreign keys point into ``players`` with
``ON DELETE CASCADE``. Nothing here touches an existing table.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auction_value_sources",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("publisher_url", sa.String(length=512), nullable=True),
        sa.Column(
            "derivation_method",
            sa.Enum(
                "z_score_budget_distribution",
                "editorial",
                "observed_platform_auctions",
                "unestablished",
                name="auction_value_derivation",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("derivation_evidence", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("data_layer", sa.String(length=32), server_default="market", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_layer = 'market'", name=op.f("ck_auction_value_sources_market_layer_only")
        ),
        sa.CheckConstraint(
            "length(derivation_evidence) > 0",
            name=op.f("ck_auction_value_sources_derivation_evidence_not_empty"),
        ),
        sa.CheckConstraint(
            "length(slug) > 0", name=op.f("ck_auction_value_sources_slug_not_empty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auction_value_sources")),
        sa.UniqueConstraint("slug", name="uq_auction_value_sources_slug"),
    )
    op.create_index("ix_auction_value_sources_slug", "auction_value_sources", ["slug"])

    op.create_table(
        "auction_value_imports",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=9), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("profile_version", sa.String(length=64), nullable=False),
        sa.Column("profile_header_contract_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_lineage", sa.JSON(), nullable=False),
        sa.Column("basis_budget", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "basis_budget_evidence",
            sa.Enum(
                "stated",
                "inferred",
                "unestablished",
                name="basis_budget_evidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("basis_team_count", sa.Integer(), nullable=True),
        sa.Column(
            "basis_team_count_evidence",
            sa.Enum(
                "stated",
                "inferred",
                "unestablished",
                name="basis_team_count_evidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("basis_roster_size", sa.Integer(), nullable=True),
        sa.Column(
            "basis_roster_size_evidence",
            sa.Enum(
                "stated",
                "inferred",
                "unestablished",
                name="basis_roster_size_evidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "basis_scoring_type",
            sa.Enum(
                "h2h_categories",
                "h2h_points",
                "h2h_each_category",
                "roto",
                "points",
                name="scoring_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column(
            "basis_scoring_type_evidence",
            sa.Enum(
                "stated",
                "inferred",
                "unestablished",
                name="basis_scoring_type_evidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("basis_category_count", sa.Integer(), nullable=True),
        sa.Column(
            "basis_category_count_evidence",
            sa.Enum(
                "stated",
                "inferred",
                "unestablished",
                name="basis_category_count_evidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("basis_note", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("needs_review_count", sa.Integer(), nullable=False),
        sa.Column("unmatched_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(basis_budget_evidence = 'unestablished' AND basis_budget IS NULL) OR (basis_budget_evidence <> 'unestablished' AND basis_budget IS NOT NULL)",
            name=op.f("ck_auction_value_imports_basis_budget_evidence_pairing"),
        ),
        sa.CheckConstraint(
            "(basis_category_count_evidence = 'unestablished' AND basis_category_count IS NULL) OR (basis_category_count_evidence <> 'unestablished' AND basis_category_count IS NOT NULL)",
            name=op.f("ck_auction_value_imports_basis_category_count_evidence_pairing"),
        ),
        sa.CheckConstraint(
            "(basis_roster_size_evidence = 'unestablished' AND basis_roster_size IS NULL) OR (basis_roster_size_evidence <> 'unestablished' AND basis_roster_size IS NOT NULL)",
            name=op.f("ck_auction_value_imports_basis_roster_size_evidence_pairing"),
        ),
        sa.CheckConstraint(
            "(basis_scoring_type_evidence = 'unestablished' AND basis_scoring_type IS NULL) OR (basis_scoring_type_evidence <> 'unestablished' AND basis_scoring_type IS NOT NULL)",
            name=op.f("ck_auction_value_imports_basis_scoring_type_evidence_pairing"),
        ),
        sa.CheckConstraint(
            "(basis_team_count_evidence = 'unestablished' AND basis_team_count IS NULL) OR (basis_team_count_evidence <> 'unestablished' AND basis_team_count IS NOT NULL)",
            name=op.f("ck_auction_value_imports_basis_team_count_evidence_pairing"),
        ),
        sa.CheckConstraint(
            "NOT (basis_budget_evidence = 'inferred' OR basis_team_count_evidence = 'inferred' OR basis_roster_size_evidence = 'inferred' OR basis_scoring_type_evidence = 'inferred' OR basis_category_count_evidence = 'inferred') OR (basis_note IS NOT NULL AND length(basis_note) > 0)",
            name=op.f("ck_auction_value_imports_inference_requires_a_note"),
        ),
        sa.CheckConstraint(
            "basis_budget IS NULL OR basis_budget > 0",
            name=op.f("ck_auction_value_imports_basis_budget_positive"),
        ),
        sa.CheckConstraint(
            "basis_category_count IS NULL OR basis_category_count > 0",
            name=op.f("ck_auction_value_imports_basis_category_count_positive"),
        ),
        sa.CheckConstraint(
            "basis_roster_size IS NULL OR basis_roster_size > 0",
            name=op.f("ck_auction_value_imports_basis_roster_size_positive"),
        ),
        sa.CheckConstraint(
            "basis_team_count IS NULL OR basis_team_count > 0",
            name=op.f("ck_auction_value_imports_basis_team_count_positive"),
        ),
        sa.CheckConstraint(
            "matched_count >= 0", name=op.f("ck_auction_value_imports_matched_count_non_negative")
        ),
        sa.CheckConstraint(
            "needs_review_count >= 0",
            name=op.f("ck_auction_value_imports_needs_review_count_non_negative"),
        ),
        sa.CheckConstraint(
            "rejected_count >= 0", name=op.f("ck_auction_value_imports_rejected_count_non_negative")
        ),
        sa.CheckConstraint(
            "row_count >= 0", name=op.f("ck_auction_value_imports_row_count_non_negative")
        ),
        sa.CheckConstraint(
            "unmatched_count >= 0",
            name=op.f("ck_auction_value_imports_unmatched_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["auction_value_sources.id"],
            name=op.f("fk_auction_value_imports_source_id_auction_value_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auction_value_imports")),
        sa.UniqueConstraint(
            "source_id",
            "season",
            "as_of_date",
            "content_sha256",
            name="uq_auction_value_imports_identity",
        ),
    )
    op.create_index("ix_auction_value_imports_as_of_date", "auction_value_imports", ["as_of_date"])
    op.create_index(
        "ix_auction_value_imports_content_sha256", "auction_value_imports", ["content_sha256"]
    )
    op.create_index("ix_auction_value_imports_season", "auction_value_imports", ["season"])
    op.create_index("ix_auction_value_imports_source_id", "auction_value_imports", ["source_id"])
    op.create_index(
        "ix_auction_value_imports_source_season", "auction_value_imports", ["source_id", "season"]
    )

    op.create_table(
        "auction_value_source_inputs",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "input_kind",
            sa.Enum(
                "projections",
                "adp",
                "observed_auctions",
                "editorial_judgement",
                name="auction_value_input_kind",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("input_label", sa.String(length=256), nullable=False),
        sa.Column(
            "our_projection_source",
            sa.Enum(
                "nba",
                "fantrax",
                "fantrax_stats_inc",
                "fantrax_rotowire",
                "fantrax_sportradar",
                "fantasypros",
                "hashtag",
                "basketball_monster",
                "darko",
                "manual",
                name="external_source",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(evidence) > 0",
            name=op.f("ck_auction_value_source_inputs_input_evidence_not_empty"),
        ),
        sa.CheckConstraint(
            "length(input_label) > 0",
            name=op.f("ck_auction_value_source_inputs_input_label_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["auction_value_sources.id"],
            name=op.f("fk_auction_value_source_inputs_source_id_auction_value_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auction_value_source_inputs")),
        sa.UniqueConstraint(
            "source_id", "input_kind", "input_label", name="uq_auction_value_source_inputs_identity"
        ),
    )
    op.create_index(
        "ix_auction_value_source_inputs_ours",
        "auction_value_source_inputs",
        ["our_projection_source"],
    )
    op.create_index(
        "ix_auction_value_source_inputs_source_id", "auction_value_source_inputs", ["source_id"]
    )

    op.create_table(
        "published_auction_values",
        sa.Column("import_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=9), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column(
            "value_kind",
            sa.Enum(
                "projected",
                "observed_market",
                name="auction_value_kind",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("value_dollars", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("value_raw", sa.String(length=32), nullable=False),
        sa.Column("source_player_id", sa.String(length=64), nullable=True),
        sa.Column("source_player_name", sa.String(length=128), nullable=False),
        sa.Column("data_layer", sa.String(length=32), server_default="market", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_layer = 'market'", name=op.f("ck_published_auction_values_market_layer_only")
        ),
        sa.CheckConstraint(
            "length(value_raw) > 0", name=op.f("ck_published_auction_values_value_raw_not_empty")
        ),
        sa.CheckConstraint(
            "value_dollars >= 0",
            name=op.f("ck_published_auction_values_value_dollars_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["auction_value_imports.id"],
            name=op.f("fk_published_auction_values_import_id_auction_value_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_published_auction_values_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_published_auction_values")),
        sa.UniqueConstraint(
            "import_id",
            "player_id",
            "value_kind",
            name="uq_published_auction_values_import_player_kind",
        ),
    )
    op.create_index(
        "ix_published_auction_values_import_id", "published_auction_values", ["import_id"]
    )
    op.create_index(
        "ix_published_auction_values_player_as_of",
        "published_auction_values",
        ["player_id", "as_of_date"],
    )
    op.create_index(
        "ix_published_auction_values_player_id", "published_auction_values", ["player_id"]
    )
    op.create_index(
        "ix_published_auction_values_player_season",
        "published_auction_values",
        ["player_id", "season"],
    )
    op.create_index("ix_published_auction_values_season", "published_auction_values", ["season"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the four market tables. Indexes go with their tables on both dialects."""
    op.drop_table("published_auction_values")
    op.drop_table("auction_value_source_inputs")
    op.drop_table("auction_value_imports")
    op.drop_table("auction_value_sources")
