"""Diff two JSON documents by **every** leaf path, not the paths you thought to check.

This repository already testifies that the technique matters and, until now,
gave you no way to perform it. From
``backend/src/hoops_gm/ingest/injury_report/cohort_evidence.py``, in
``_operational_artifacts``:

    This bit me on a regeneration: run from ``backend/`` rather than the data
    root, the section silently emptied and three files' sizes and hashes
    vanished from the manifest with nothing marking their absence. The cohort
    numbers were byte-identical, so a diff of the interesting fields showed
    nothing wrong. **Only a whole-leaf diff caught it.**

The next reader was told the tool was decisive and handed nothing. This is the
tool.

## The value is entirely in the word *all*

A diff scoped to the fields you expect to move is precisely how that
degradation passed. Every cohort number was byte-identical - 13,789 canonical
observations, 13,598 joined, every status count - while three file hashes
quietly left a section nobody was watching. **A scoped diff cannot report a
field you did not think to name**, and the fields you do not think to name are
where provenance lives.

It is also what supports the *negative* claim, which is the harder one. After a
rebase, ``1 path added, 0 removed, 9 values changed - all of them
operator.commands plus one fingerprint`` is a defensible statement that no
number moved, and so an earlier from-scratch reproduction of the artefact still
applies unaltered. Without a whole-leaf comparison that sentence is an
assertion, and the reviewer has to re-run everything.

## Empty containers are leaves here, deliberately

``{"files": {}}`` reports one leaf, ``files`` with value ``{}`` - not zero
leaves. Otherwise a section collapsing to empty appears only as a handful of
removals, and the very shape this tool exists to catch is a section that
emptied. Absent evidence must be distinguishable from negative evidence, and
that applies to the diff as much as to the manifest it reads.

## What it cannot tell you, which is the important half

It compares two JSON documents by leaf path and value. **It cannot tell you a
value is wrong, only that it moved - or didn't.** Two manifests that agree at
every leaf are equally consistent with both being correct and both being
generated by the same broken code against the same broken input. A leaf-level
agreement is a statement about *change*, never about *truth*.

Also invisible to it: anything not expressible as a JSON leaf, key ordering
(dicts are compared by key, not position), and the meaning of any path whose
key contains ``.`` or ``[``, which will render ambiguously against the path
syntax below. It reports; it does not judge which movements were intended.

## Usage

    python scripts/manifest_leaf_diff.py <before> <after>

Each argument is either a path on disk or a git ``<ref>:<path>``, so the
regeneration case is one line:

    python scripts/manifest_leaf_diff.py \\
        origin/main:docs/adapters/cohort.json docs/adapters/cohort.json

Exits 1 if any leaf was **removed**, 0 otherwise. A removal is not
automatically wrong - but it is the one direction that degrades an artefact
while every other check stays green, which is the whole story above.

Exit **2** means it refused and compared nothing. That is a separate code from
1 on purpose: an error that shares an exit code with a finding is an error that
gets read as a finding, and this tool exists because of a class of defect that
looks like an answer.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]

MAX_RENDER = 120


def _leaves(doc: Any, prefix: str = "") -> dict[str, Any]:
    """Flatten to ``{path: scalar}``, treating an empty container as a leaf.

    The empty-container rule is load-bearing rather than tidy: a section that
    collapses to ``{}`` must show up as one *changed* leaf, not as silence plus
    a scatter of removals somewhere below it.
    """
    if isinstance(doc, dict) and doc:
        out: dict[str, Any] = {}
        for key, value in doc.items():
            child = f"{prefix}.{key}" if prefix else str(key)
            out |= _leaves(value, child)
        return out
    if isinstance(doc, list) and doc:
        out = {}
        for index, value in enumerate(doc):
            out |= _leaves(value, f"{prefix}[{index}]")
        return out
    return {prefix or "<root>": doc}


def _render(value: Any) -> str:
    text = json.dumps(value, sort_keys=True, default=str)
    if len(text) > MAX_RENDER:
        return f"{text[:MAX_RENDER]}... ({len(text)} chars)"
    return text


def _parse(text: str, spec: str) -> Any:
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        print(f"{spec!r} is not valid JSON: {exc}. Nothing was compared.", file=sys.stderr)
        raise SystemExit(2) from exc


def _load(spec: str) -> Any:
    """Read a JSON document from disk, or from git when the path is not there.

    Disk is tried first so a Windows path such as ``C:\\...\\cohort.json`` is
    never mistaken for a ``ref:path`` pair on account of its colon.
    """
    candidate = Path(spec)
    if candidate.exists():
        return _parse(candidate.read_text(encoding="utf-8"), spec)
    if ":" in spec:
        try:
            raw = subprocess.run(
                ("git", "show", spec),
                cwd=REPO,
                check=True,
                capture_output=True,
            ).stdout
        except subprocess.CalledProcessError as exc:
            detail = exc.stderr.decode("utf-8", errors="replace").strip()
            print(
                f"{spec!r} is not a file on disk, and `git show {spec}` failed:\n  {detail}",
                file=sys.stderr,
            )
            raise SystemExit(2) from exc
        return _parse(raw.decode("utf-8"), spec)
    print(
        f"{spec!r} is not a file on disk and holds no ':', so it cannot be a "
        f"git <ref>:<path> either. Nothing was compared.",
        file=sys.stderr,
    )
    raise SystemExit(2)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("before", help="a path on disk, or a git <ref>:<path>")
    parser.add_argument("after", help="a path on disk, or a git <ref>:<path>")
    args = parser.parse_args(argv)

    before = _leaves(_load(args.before))
    after = _leaves(_load(args.after))

    added = sorted(after.keys() - before.keys())
    removed = sorted(before.keys() - after.keys())
    changed = sorted(k for k in before.keys() & after.keys() if before[k] != after[k])

    print(f"before {args.before}: {len(before)} leaves")
    print(f"after  {args.after}: {len(after)} leaves")
    print(f"{len(added)} added    {len(removed)} removed    {len(changed)} changed")
    print()

    if added:
        print(f"ADDED ({len(added)}):")
        for path in added:
            print(f"  + {path} = {_render(after[path])}")
        print()
    if removed:
        print(f"REMOVED ({len(removed)}):")
        for path in removed:
            print(f"  - {path} = {_render(before[path])}")
        print()
    if changed:
        print(f"CHANGED ({len(changed)}):")
        for path in changed:
            print(f"  ~ {path}")
            print(f"      before: {_render(before[path])}")
            print(f"      after:  {_render(after[path])}")
        print()

    if not (added or removed or changed):
        print("Identical at every leaf.")
        print()

    print("A leaf-level agreement is a statement about change, never about truth:")
    print("two documents can agree everywhere and both be wrong. The exit code")
    print("flags removals only - on a regeneration most changes are the point, and")
    print("only you know which paths were supposed to move.")
    return 1 if removed else 0


if __name__ == "__main__":
    raise SystemExit(main())
